Run the zip-artifacts job in save-atomic-files workflow (#338)
* remove brackets

* testing:  would be reverted

* modify if statement

* Add spaces in the conditional statement

* Create a job for ref-check in save-atomic-data files

* Change the check to workflow dispatch

* uncomment cron job code

* Add comments

* Comment on refdata comparison outcome

diff --git a/.github/workflows/bridge.yml b/.github/workflows/bridge.yml
--- a/.github/workflows/bridge.yml
+++ b/.github/workflows/bridge.yml
@@ -5,7 +5,7 @@ on:
     outputs:
       ref-check-trig:
         value: ${{ jobs.tardis-build.outputs.step-ref-check-trig}}
-  workflow_dispatch:
+  workflow_dispatch: # for running manually
 
         
 env:
@@ -88,7 +88,7 @@ jobs:
     needs: carsus-build
     runs-on: ubuntu-latest
     outputs:
-      step-ref-check-trig: ${{ steps.ref-equal-check.outputs.triggered }}
+      step-ref-check-trig: ${{ steps.ref-equal-check.outcome }} # success or failure of refdata comparison
 
     steps:
       - uses: actions/checkout@v2
@@ -169,4 +169,14 @@ jobs:
       
       - name: Check if reference data are equal
         id: ref-equal-check
+        continue-on-error: true
         run: if [ "$(cat ../refdata_compare_result)" == "REFDATA COMPARISON FAILED" ]; then exit 1; fi
+
+      # continue-on-error check would display a green tick even when the step passes
+      # but is necessary for other steps to run
+      # if the workflow was called by save-atomic-files workflow(the only other option)
+      # and refdata comparison failed this workflow would pass but the 
+      # bridge-ref-check job in save-atomic-files about refdata comparison would fail
+      - name: Fail the workflow if reference data check fails
+        if: github.event_name == 'workflow_dispatch' && steps.ref-equal-check.outcome == 'failure'
+        run: exit 1
